from __future__ import annotations

from .crops import (
    is_cultura_valida,
    listar_culturas,
    normalizar_cultura,
)
from .dates import (
    MESES_PT,
    anos_para_safra,
    lista_safras,
    month_to_number,
    normalizar_safra,
    periodo_safra,
    safra_anterior,
    safra_atual,
    safra_para_anos,
    safra_posterior,
    validar_safra,
)
from .encoding import decode_content, detect_encoding, detect_encoding_chain
from .municipalities import (
    buscar_municipios,
    coordenada_para_municipio,
    ibge_para_municipio,
    municipio_para_ibge,
    total_municipios,
)
from .numeric import parse_numeric_br, safe_float
from .regions import (
    BIOMAS,
    BIOMAS_VALIDOS,
    UFS_VALIDAS,
    ibge_para_uf,
    listar_regioes,
    listar_ufs,
    normalizar_bioma,
    normalizar_municipio,
    normalizar_praca,
    normalizar_uf,
    uf_para_ibge,
    uf_para_nome,
    uf_para_regiao,
    validar_uf,
)
from .units import (
    converter,
    preco_saca_para_tonelada,
    preco_tonelada_para_saca,
    sacas_para_toneladas,
    toneladas_para_sacas,
)

__all__: list[str] = [
    "BIOMAS",
    "BIOMAS_VALIDOS",
    "MESES_PT",
    "UFS_VALIDAS",
    "buscar_municipios",
    "coordenada_para_municipio",
    "converter",
    "decode_content",
    "detect_encoding",
    "detect_encoding_chain",
    "ibge_para_municipio",
    "ibge_para_uf",
    "is_cultura_valida",
    "listar_culturas",
    "lista_safras",
    "month_to_number",
    "listar_regioes",
    "listar_ufs",
    "municipio_para_ibge",
    "normalizar_bioma",
    "normalizar_cultura",
    "normalizar_municipio",
    "normalizar_praca",
    "normalizar_safra",
    "normalizar_uf",
    "parse_numeric_br",
    "safe_float",
    "periodo_safra",
    "preco_saca_para_tonelada",
    "preco_tonelada_para_saca",
    "sacas_para_toneladas",
    "safra_anterior",
    "safra_atual",
    "safra_para_anos",
    "safra_posterior",
    "toneladas_para_sacas",
    "total_municipios",
    "uf_para_ibge",
    "uf_para_nome",
    "uf_para_regiao",
    "validar_safra",
    "validar_uf",
    "anos_para_safra",
]
