"""agrobr - Dados agricolas brasileiros em uma linha de codigo."""

from __future__ import annotations

__version__ = "1.0.5"
__author__ = "Bruno"

from agrobr import (
    abiove,
    alt,
    ana,
    anda,
    antaq,
    b3,
    bcb,
    cepea,
    comexstat,
    comtrade,
    conab,
    contracts,
    datasets,
    defensivos,
    deral,
    desmatamento,
    embrapa_solos,
    funai,
    ibama,
    ibge,
    icmbio,
    imea,
    incra,
    inmet,
    lista_suja,
    mapbiomas,
    mapbiomas_alerta,
    nasa_power,
    noticias_agricolas,
    queimadas,
    rio_verde,
    rnc,
    sfb,
    usda,
    zarc,
)
from agrobr.config import configure
from agrobr.datasets.deterministic import deterministic
from agrobr.exceptions import (
    AgrobrError,
    ContractViolationError,
    ParseError,
    SourceUnavailableError,
)
from agrobr.models import MetaInfo

__all__ = [
    "abiove",
    "alt",
    "ana",
    "anda",
    "antaq",
    "b3",
    "bcb",
    "cepea",
    "comexstat",
    "comtrade",
    "conab",
    "configure",
    "contracts",
    "datasets",
    "defensivos",
    "deral",
    "desmatamento",
    "embrapa_solos",
    "deterministic",
    "funai",
    "ibama",
    "ibge",
    "icmbio",
    "imea",
    "incra",
    "inmet",
    "lista_suja",
    "mapbiomas",
    "mapbiomas_alerta",
    "nasa_power",
    "noticias_agricolas",
    "queimadas",
    "rio_verde",
    "rnc",
    "sfb",
    "usda",
    "zarc",
    "AgrobrError",
    "ContractViolationError",
    "ParseError",
    "SourceUnavailableError",
    "MetaInfo",
    "__version__",
]
